# Generated by Django 5.2.13 on 2026-06-24 08:19

from django.db import migrations


def seed_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    SiteSettings.objects.create(
        site_name='Call Driver Agency',
        tagline='Your Reliable Travel Partner',
        contact_email='info@calldriveragency.com',
        contact_phone='+91 79092 51054',
        address=(
            'Thalakkadathur, Tirur\n'
            'Malappuram, Kerala – 676103'
        ),
        working_hours='Mon - Sun: 24/7',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_site_settings, reverse_code=migrations.RunPython.noop),
    ]
