# Generated by Django 5.2.13 on 2026-06-24 08:11

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_image_servicecategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a background video for this service', null=True, upload_to=services.models.service_video_path),
        ),
    ]
