# Generated by Django 5.2.15 on 2026-06-23 09:57

import drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_image',
            field=models.ImageField(blank=True, help_text='Upload a clear photo of your driving license', null=True, upload_to=drivers.models.license_image_path),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=drivers.models.profile_image_path),
        ),
    ]
