# Generated by Django 5.2.13 on 2026-06-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driverprofile_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
