# Generated by Django 5.2.15 on 2026-06-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type'], name='accounts_cu_user_ty_97b0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_verified'], name='accounts_cu_is_veri_c594de_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['-date_joined'], name='accounts_cu_date_jo_36131c_idx'),
        ),
    ]
