# Generated by Django 5.2.15 on 2026-06-23 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('drivers', '0003_alter_driverprofile_is_available_and_more'),
        ('services', '0002_alter_service_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_bo_status_72dd85_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pickup_time'], name='bookings_bo_pickup__26c66b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_bo_created_1720a2_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingstatuslog',
            index=models.Index(fields=['booking', 'created_at'], name='bookings_bo_booking_93bd69_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='bookings_pa_status_3e8a31_idx'),
        ),
    ]
