# Generated by Django 5.2.13 on 2026-06-24 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status_alter_payment_status_and_more'),
        ('drivers', '0004_alter_driverprofile_phone'),
        ('services', '0004_service_image_servicecategory_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstatuslog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff_location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'created_at'], name='bookings_bo_custome_f17938_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['driver', 'created_at'], name='bookings_bo_driver__a432bd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'status'], name='bookings_pa_booking_bf00c8_idx'),
        ),
    ]
